[build]
    functions = "serverless/"
[dev]
    targetPort = 3000
[functions]
    directory = "serverless/"
    node_bundler = "esbuild"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
